services:
  postgres:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./prepare-db.sql:/docker-entrypoint-initdb.d/prepare-db-django.sql
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "converter"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    volumes:
      - ./docker/servers.json:/pgadmin4/servers.json
