# Generated by Django 5.1.2 on 2024-10-27 20:47

import django.core.validators
import django.db.models.deletion
import melqui_system.apps.subscription.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, validators=[melqui_system.apps.subscription.validators.validate_cpf], verbose_name='CPF')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('cell_phone', models.CharField(max_length=32, validators=[melqui_system.apps.subscription.validators.cell_phone_validator], verbose_name='Numero de Telefone (WhatApp)')),
                ('birthday', models.DateField(verbose_name='Data de aniversario')),
                ('cep', models.CharField(verbose_name='CEP')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], verbose_name='Estado')),
                ('city', models.CharField(verbose_name='Cidade')),
                ('neighborhood', models.CharField(verbose_name='Bairro')),
                ('street', models.CharField(verbose_name='Rua')),
                ('number', models.CharField(verbose_name='Numero')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('indicated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indications', to='subscription.subscription', verbose_name='Indicado por')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_date', models.DateTimeField(verbose_name='Data de aprovação')),
                ('approved', models.BooleanField(verbose_name='Aprovado')),
                ('comments', models.TextField(default='', verbose_name='Comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
            },
        ),
    ]
